cbt/urls.py
from django.urls import path

from cbt.views import (
    CognitiveDistortionListView,
    ThoughtDetailView,
    ThoughtListView,
    ThoughtCreateView,
    home,
)

app_name = "cbt"
urlpatterns = [
    path(
        "",
        home,
        name="home",
    ),
    path(
        "cognitive-distortions/",
        CognitiveDistortionListView.as_view(),
        name="cognitive-distortion-list",
    ),
    path(
        "thoughts/",
        ThoughtListView.as_view(),
        name="thought-list",
    ),
    path(
        "thoughts/create/",
        ThoughtCreateView.as_view(),
        name="thought-create",
    ),
    path(
        "thoughts/create/<int:cognitive_distortion_id>/",
        ThoughtCreateView.as_view(),
        name="thought-create",
    ),
    path(
        "thoughts/<int:pk>/",
        ThoughtDetailView.as_view(),
        name="thought-detail",
    ),
]

config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

from config.settings import THE_SITE_NAME

urlpatterns = [
    path(
        "",
        TemplateView.as_view(
            template_name="home.html",
            extra_context={"the_site_name": THE_SITE_NAME},
        ),
        name="home",
    ),
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("journals/", include("self_enquiry.urls")),
    path("vitals/", include("vitals.urls")),
    path("cbt/", include("cbt.urls")),
    path("pharma-tracker/", include("pharma_tracker.urls")),
]

self_enquiry/urls.py
from django.urls import path

from self_enquiry.views import JournalListView, JournalDetailView
from self_enquiry.views import JournalCreateView, JournalUpdateView
from self_enquiry.views import JournalDeleteView, JournalConfirmDeleteView


app_name = "self_enquiry"
urlpatterns = [
    path(
        "create/",
        JournalCreateView.as_view(),
        name="create",
    ),
    path(
        "list/",
        JournalListView.as_view(),
        name="list",
    ),
    path(
        "<int:pk>/detail/",
        JournalDetailView.as_view(),
        name="detail",
    ),
    path(
        "<int:pk>/update/",
        JournalUpdateView.as_view(),
        name="update",
    ),
    path(
        "<int:pk>/delete/",
        JournalDeleteView.as_view(),
        name="delete",
    ),
    path(
        "<int:pk>/confirm-delete/",
        JournalConfirmDeleteView.as_view(),
        name="confirm-delete",
    ),
]

vitals/urls.py
from django.urls import path

from vitals.views import BloodPressureCreateView, BloodPressureListView, home

app_name = "vitals"
urlpatterns = [
    path(
        "",
        home,
        name="home",
    ),
    path(
        "bloodpressures/",
        BloodPressureListView.as_view(),
        name="bloodpressure-list",
    ),
    path(
        "bloodpressures/create/",
        BloodPressureCreateView.as_view(),
        name="bloodpressure-create")
]

base/models.py
from django.db import models


class CreatedUpdatedBase(models.Model):
    """
    An abstract base class model that provides self-updating `created` and
    `updated` fields.
    """

    created = models.DateTimeField(
        "Created",
        auto_now_add=True,
        help_text="The date and time this object was created.",
    )
    updated = models.DateTimeField(
        "Updated",
        auto_now=True,
        help_text="The date and time this object was last updated.",
    )

    class Meta:
        abstract = True

templates/applications.html
{% block content %}
<h3>Applications</h3>
<ul>
    <li><a href="{% url 'home' %}">Project Home</a></li>
    <li><a href={% url "vitals:bloodpressure-list" %}>Blood Pressures</a></li>
    <li><a href={% url "self_enquiry:list" %}>Self Enquiry</a></li>
    <li>
        CBT
        |
        <a href={% url "cbt:cognitive-distortion-list" %}>Cognitive Distortions</a>
        |
        <a href={% url "cbt:thought-list" %}>Thoughts</a>
        |
        <a href={% url "cbt:thought-create" %}>Create New Thought</a>
    </li>
</ul>

{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock title %}</title>
    </head>
    <body>
        <main>
            {% include 'user.html' %}

            {% if user.is_staff %}
                {% include 'staff.html' %}
            {% endif %}

            {% if user.is_authenticated %}
                {% include "applications.html" %}
            {% endif %}

            {% block content %}
            {% endblock content %}
        </main>
    </body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}{{ the_site_name }} - Home{% endblock %}

{% block content %}
<h1>Home</h1>

{% endblock content %}

templates/staff.html
<div>
    <a
        href="https://github.com/brucestull/health-tracker"
        target="_blank"
        >
        Health Tracker - GitHub Repository
    </a>
    <br>
    <a href={% url 'admin:index' %}>
        Django Admin Interface
    </a>
    <br>
</div>

templates/user.html
<div>
    {% if user.is_authenticated %}
        <span>Greetings, {{ user.username | capfirst }}!</span>
        <br>
        <a href="{% url 'logout' %}">Log Out</a>
        |
        <a href="{% url 'detail' user.id %}">User Information</a>
        |
        <a href="{% url 'edit' user.id %}">Edit User Information</a>
        |
        <a href="{% url 'password_change' %}">Password Change</a>
        |
        <a href="{% url 'password_reset' %}">Password Reset</a>
    {% else %}
        <p>We are not sure who you are, you are welcome to do one of the following:</p>
        <a href="{% url 'login' %}">Log In</a>
        |
        <a href="{% url 'signup' %}">Sign Up</a>
    {% endif %}
</div>